### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Rain436** [socchn0123/okozukai-kannri#1]
このあぷりはとてｍくー！る

**Comment by Rain436** [comment]
あと操作方法教えてください

**Comment by socchn0123** [comment]
![image](https://github.com/user-attachments/assets/dcd1699a-e9f7-4f26-b4ad-e483203f647f)
この画像みたいに数値を入力して更新をﾎﾟﾁｯってすればいける

**Comment by Rain436** [comment]
あとtkinter使うのはやめましょうcustomtkinterに移行しましょう

**Comment by socchn0123** [comment]
おｈ
